language: js

node_js:
  - "10"

before_install:
  - npm i -g npm
  - openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv -in github_deploy_key.enc -out github_deploy_key -d

before_script:
  - npm install
  - mkdir -p dist/

script:
  - npm run coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: required
addons:
  chrome: stable
